### ISSUE TITLE
json文件的格式

### ISSUE THREAD

**Issue by jujiubobo** [Nian-Chen/w2v2_czc#1]
大佬好，我想跑一下这个代码，学习一下大佬思想，但是第三步不太清楚，”根据data_dir中的text构建词表lang_char.txt，转为vocab.json“的json文件格式是怎样的啊？

**Comment by Nian-Chen** [comment]
和huggingface/transformers的格式一致，我上传了个demo你可以看看，在processor_en_demo文件夹下
